export const defaultStoryModeId = "thulak";

export const storyModes = [
  {
    id: "thulak",
    secret: false,
    shortcutLabel: "T",
    titleKey: "mode.thulak.title",
    menuKey: "mode.thulak.menu",
    descriptionKey: "mode.thulak.description",
    aliases: ["thulak", "canon", "canonical", "main"]
  },
  {
    id: "designer",
    secret: true,
    shortcutLabel: "D",
    titleKey: "mode.designer.title",
    menuKey: "mode.designer.menu",
    descriptionKey: "mode.designer.description",
    unlockKey: "mode.designer.unlock",
    aliases: ["designer", "design", "designer-mode", "secret"]
  }
];

export function getStoryMode(modeId) {
  return storyModes.find((mode) => mode.id === modeId) ?? storyModes[0];
}

export function resolveStoryModeId(value) {
  if (!value) {
    return defaultStoryModeId;
  }

  const normalized = String(value).trim().toLowerCase();

  for (const mode of storyModes) {
    if (mode.id === normalized || mode.aliases?.includes(normalized)) {
      return mode.id;
    }
  }

  return defaultStoryModeId;
}

export const storyModeLocales = {
  designer: {
    "pt-BR": {
      "mode.designer.title": "A Jornada do Designer que Descobriu o Terminal",
      "mode.designer.menu": "Jornada do Designer",
      "mode.designer.description": "Uma parodia secreta sobre design, terminal e escolhas duvidosas.",
      "mode.designer.unlock": "SEGREDO DESBLOQUEADO: A Jornada do Designer que Descobriu o Terminal.",
      "ui.ending": "FIM DE PROTOTIPO",
      "ui.footer": "Designer Terminal Engine v0.1",
      "item.mentor_token": "cartao de espacamentos do mentor",
      "item.black_grimoire": "manual proibido do terminal",
      "chapter.1.title": "Introducao ao Briefing",
      "chapter.1.summary": "Voce ainda acha que vai abrir o Figma. O terminal tem outros planos.",
      "chapter.2.title": "As Catacumbas do Wireframe",
      "chapter.2.summary": "Pastas mortas, flows esquecidos e notas sem dono.",
      "chapter.3.title": "Nas Masmorras do Backlog",
      "chapter.3.summary": "Tickets que nao morrem, escopos que incham e dry-runs sem fim.",
      "chapter.4.title": "Os Segredos do Design System Ancestral",
      "chapter.4.summary": "Tokens proibidos, grids esquecidos e a antiga obsessao pelo azul perfeito.",
      "chapter.5.title": "A UX com Seus Horrores",
      "chapter.5.summary": "A fuga da biblioteca e do templo do layout absoluto.",
      "rules.intro": "Voce pode jogar esta parodia so escolhendo as opcoes da tela, ou usar um d6 para simular aprovacoes, retrabalho, coragem para defender uma ideia e resistencia a reunioes que poderiam ser um e-mail.",
      "rules.note": "O dado continua opcional. Se preferir, voce pode apenas escolher como esse designer vai perder a paz.",
      "menu.subtitle": "Um designer jovem encontra o terminal e descobre que alinhamento, espaco e sanidade sao conceitos negociaveis.",
      "menu.intro": "No dia em que completa vinte anos, voce jura que vai trabalhar so com telas bonitas, grids limpos e comentarios objetivos. Entao aparece um manual proibido de terminal, um mentor ausente e a promessa indecente de controlar o caos de um projeto inteiro sem abrir uma unica janela do Figma.",
      "scene.intro_home.body": "O estudio de Freixo da Neblina desperta com cheiro de cafe velho, teclado mecanico e pavor silencioso de segunda-feira. Hoje voce faz vinte anos. Designer junior, meio-elfo, ultimo pupilo do lendario Edrin da Direcao de Arte, voce se prepara para sair da bolha dos mockups academicos e encarar projetos de verdade. Mas a manha chega torta: um freelancer foi encontrado desacordado na estrada do norte, e sua bolsa traz marcas estranhas, como se tivesse sido fechada por uma entidade que odeia alinhamento manual.",
      "scene.intro_home.choice_tower": "Subir ao antigo estudio de Edrin antes de aceitar o briefing",
      "scene.intro_home.choice_inn": "Ir direto ao coworking ver a bolsa do freelancer",
      "scene.mentor_room.body": "O estudio de Edrin ainda guarda post-its antigos, tipografias anotadas a lapis e o cheiro seco de um projetor aposentado. Sobre uma mesa torta, voce encontra o cartao de espacamentos que ele erguia sempre que algum aluno queria resolver tudo com sombra e gradiente: 'Toda interface cobra alguma coisa. A que promete controle absoluto cobra primeiro a paciencia da equipe.' Ao lado, ha um bilhete inacabado sobre ferramentas antigas que primeiro seduzem o ego e so depois devoram a agenda inteira.",
      "scene.mentor_room.choice_keep_token": "Levar o cartao de espacamentos e descer para o caos",
      "scene.mentor_room.choice_leave": "Guardar a licao do mentor e sair sem mexer em nada",
      "scene.intro_study.body": "No coworking, o freelancer ja foi levado para a sala silenciosa, mas a bolsa continua sobre a mesa principal sob os olhares culpados do time. Como voce e o unico por perto que ainda sabe onde fica a pasta de fontes e como abrir um terminal sem suar frio, pedem que examine o fecho e os adesivos. Quando abre a bolsa, encontra um manual preto, frio como um monitor desligado. Mesmo fechado, ele parece pulsar. O titulo promete uma arte esquecida: dominar projetos inteiros sem depender de janelas, paineis ou cliques gentis.",
      "scene.intro_study.choice_open": "Abrir o manual proibido",
      "scene.intro_study.choice_origin": "Inspecionar marcas e tentar descobrir de onde veio",
      "scene.intro_study.choice_refuse": "Fechar a bolsa e fingir que nada disso e problema seu",
      "scene.traveler_markings.body": "Sob o forro da bolsa, voce encontra bolsos secretos com cabos sem etiqueta, um mapa do predio rabiscado e tres paginas de diario grudadas por cafe seco. Nao ha nome, so frases febris: 'o subsolo onde os devs falam baixo', 'os guardas que revisam sem piscar', 'a Gema Azul nao e um token, e uma doenca'. Na ultima linha, a caligrafia desce como quem tentou escrever durante uma daily de quarenta minutos. Ha ainda po azul nos cantos da bolsa, fino como pigmento de branding premium.",
      "scene.traveler_markings.choice_journal": "Ler o diario inteiro e voltar ao manual",
      "scene.traveler_markings.choice_shrine": "Ir ate a sala silenciosa ver o estado do freelancer",
      "scene.shrine_body.body": "Na sala silenciosa, o freelancer repousa numa cadeira ergonomica que ja desistiu do proprio nome. O rosto envelheceu dez sprints em uma noite. Quando voce afasta o cachecol do pescoco, encontra uma marca estreita perto da clavicula, fina demais para ser alca de mochila e fria demais para ser so exaustao. Ao redor, ha po azul esmaecido, como se alguem tivesse moido um manual de marca e soprado os restos dentro da alma.",
      "scene.shrine_body.choice_wound": "Estudar a marca e levar essa imagem consigo",
      "scene.shrine_body.choice_leave": "Cobrir o freelancer e sair antes que a culpa sente ao seu lado",
      "scene.whispering_book.body": "As paginas se movem quase sozinhas sob a luz torta do escritorio. Ha relatos de equipes que abandonaram interfaces graficas, de designers que passaram a compor fluxos por texto, de pessoas que organizaram caos, assets e deploys sem tocar num painel lateral. Desde que Edrin sumiu do mercado, voce passa os dias fingindo que o design ainda e feito so de forma e bom gosto. Agora o manual poe em palavras um desejo que voce nunca confessou: se o projeto pode ser descrito, talvez possa ser controlado. O livro nao fala apenas de produtividade. Ele responde ao seu medo de nunca dar conta. E chama pelo seu nome.",
      "scene.whispering_book.choice_follow_call": "Seguir o mapa oculto ate o subsolo indicado",
      "scene.whispering_book.choice_resist": "Lutar contra o fascinio e sair para tomar ar",
      "scene.whispering_book.choice_token": "Apertar o cartao de Edrin e ir mesmo assim",
      "scene.camp_retreat.body": "Do lado de fora, o ar frio devolve sons que sempre pareceram normais: uma notificação distante, uma moto na rua, alguem repetindo 'vamos alinhar offline'. Voce tenta se agarrar a isso, repetir exercicios de respiracao, lembrar a voz de Edrin dizendo que nenhuma ferramenta salva briefing ruim. Nao adianta. A cada piscada, ve linhas de comando, layouts surgindo de texto puro e a promessa indecente de nunca mais perder vinte minutos procurando o botao certo. Quanto mais tenta negar, mais o terminal parece uma forma de vida eterna para quem esta cansado de revisao infinita.",
      "scene.camp_retreat.choice_return": "Ceder ao chamado e seguir o mapa do manual",
      "scene.camp_retreat.choice_shrine": "Passar primeiro pela sala silenciosa e rever o freelancer",
      "scene.camp_retreat.choice_end": "Chamar um carro e desaparecer antes do proximo alinhamento",
      "scene.threshold_road.body": "Antes do almoco, voce deixa o andar principal para tras e segue a rota rabiscada entre as paginas do manual proibido. O caminho cruza salas abandonadas, um deposito de brindes de campanha e corredores onde morreram centenas de impressos feitos em prazo impossivel. O livro pulsa sob seu braco em pequenos intervalos, como se soubesse que cada passo o afasta do conforto da interface e o aproxima de algo que escreve mais rapido do que pensa.",
      "scene.threshold_road.choice_ossuary": "Examinar o deposito dos projetos antigos",
      "scene.threshold_road.choice_press_on": "Seguir direto para a antiga capela do servidor",
      "scene.threshold_road.choice_turn_back": "Parar e reconsiderar antes de descer mais",
      "scene.war_ossuary.body": "Ao afastar caixas e mockups impressos, voce nao encontra premio nem portfolio, mas restos de campanhas antigas, pantones mortos e um esqueleto de marca que um dia foi chamado de inovador. E a primeira vez que voce encara de perto um projeto legado: cartazes pesados, naming ruim e um mascote corporativo com presas de orc. O choque nao vem do horror exotico, mas da prova de que alguem defendeu aquilo numa reuniao. Entre papeis empenados ha contas pretas de plastico e uma ficha azul com um circulo no centro, como um token de interface que se recusa a morrer.",
      "scene.war_ossuary.choice_search": "Guardar a lembranca e seguir para a capela do servidor",
      "scene.war_ossuary.choice_leave": "Recolocar tudo no lugar e fingir respeito pelos mortos do branding",
      "scene.chapel_yard.body": "A antiga capela do servidor surge entre paredes frias como um showroom enterrado. Parte do forro cedeu, cabos grossos atravessam o teto e o ar cheira a poeira, metal e fonte sem licença. Perto da entrada, repousa o notebook do freelancer, morto sem bateria e coberto por adesivos de stacks que talvez ele nunca tenha usado. Sob a sujeira do hall, um mural quase apagado mostra uma figura ajoelhada diante de um botao azul sustentado por maos esqueleticas. Alguem raspou a pintura com odio, mas nao conseguiu apagar a devocao.",
      "scene.chapel_yard.choice_descend": "Cruzar o hall e descer ao subsolo",
      "scene.chapel_yard.choice_fresco": "Examinar o mural antes de entrar",
      "scene.chapel_yard.choice_leave": "Recuar enquanto ainda existe vida fora disso",
      "scene.entry_hall.body": "Guiado pelo manual e por uma curiosidade que ja virou ambicao, voce cruza a capela do servidor e chega ao hall de entrada do subsolo. Colunas rachadas sustentam o teto, manequins sem rosto parecem revisar seu portfolio e a umidade traz cheiro de metal quente, cafe esquecido e deadline vencida. A direita, um corredor de monitores azuis pulsa como se fosse vivo. Ao centro, uma mesa de pedra e cabos sustenta um altar de tokens visuais. A esquerda, nichos profundos guardam pastas de campanhas enterradas sob silencio administrativo.",
      "scene.entry_hall.choice_altar": "Examinar o altar de tokens",
      "scene.entry_hall.choice_gallery": "Entrar na galeria dos projetos sepultados",
      "scene.entry_hall.choice_torch": "Tomar uma luz de manutencao e seguir o corredor pulsante",
      "scene.altar_room.body": "Sobre o altar nao ha oferendas comuns, apenas guias de estilo partidos, grids impressos e pequenos retangulos alinhados como se formassem uma frase secreta em oito pontos. O manual vibra em suas maos. Nas margens de uma pagina antes vazia, novas linhas surgem em ferrugem azulada. Elas falam de um herdeiro, de interfaces interiores e de uma vontade que se recusa a usar margem arbitraria. Nao e um texto para qualquer leitor. E um texto para alguem disposto a chamar isso de sistema.",
      "scene.altar_room.choice_read_margin": "Ler as novas linhas ate o fim",
      "scene.altar_room.choice_leave": "Afastar-se antes que a tipografia invada o juizo",
      "scene.scroll_vision.body": "Ao terminar a leitura, voce cambaleia. Por um instante ja nao esta no subsolo, mas num auditorio enterrado muito abaixo, diante de um trono vazio cercado por wireframes coroados. Algo observa por tras daquele assento, paciente como guideline e faminto como retrabalho. Entao vem um pensamento que nao nasceu de voce: 'O alinhamento e uma prisao para os pequenos. Para voce, sera imperio.' Nao soa como promessa. Soa como onboarding.",
      "scene.scroll_vision.choice_forward": "Seguir a memoria do auditorio ate a proxima porta",
      "scene.scroll_vision.choice_retreat": "Firmar a respiracao e voltar ao corredor",
      "scene.bone_gallery.body": "Os nichos da galeria guardam campanhas mortas, prototipos empoeirados e correntes de comentarios presos a hooks de pedra. No fundo, uma figura esta acorrentada a uma cadeira: nem criativo, nem plenamente aposentado. A pele se agarrou aos ossos como quem dormiu em iluminacao ruim por tres anos, e os dedos ainda fazem pequenos gestos no ar, como se ajustassem um frame invisivel. E a primeira vez que voce entende um stakeholder morto-vivo nao como meme, mas como ofensa material ao descanso da equipe.",
      "scene.bone_gallery.choice_chain": "Aproximar-se da figura acorrentada",
      "scene.bone_gallery.choice_leave": "Sair da galeria e buscar o corredor principal",
      "scene.grave_answer.body": "Quando voce se aproxima, o rosto ressecado se ergue com o estalo lento de alguem que vai dizer 'tenho so um ajuste'. Nao ha vida ali, apenas opiniao remanescente. Um olho seco ainda ocupa a orbita como uma bolinha de mockup desalinhada, e a boca se abre devagar demais para parecer pressa. Antes que qualquer som saia, o manual aquece sob seu braco, como se reconhecesse naquela ruina uma fonte inesgotavel de feedback. O ar fica pesado de um jeito quase corporativo, como se o proprio silencio esperasse um pitch.",
      "scene.grave_answer.choice_question": "Usar o manual e exigir que o morto opine",
      "scene.grave_answer.choice_mercy": "Tocar o cartao de Edrin em sua testa e conceder silencio",
      "scene.grave_answer.choice_leave": "Recuar sem descobrir quantas revisoes ainda vivem ali",
      "scene.torch_corridor.body": "Os monitores azuis estremecem sem vento quando voce se aproxima. Adiante, sombras finas se erguem do chao: esqueletos de QA e compliance, cada um montado com ossos humanos comuns, mas movidos por uma vontade de apontar detalhes que ninguem viu. Na parede ao lado, um sigilo circular responde ao manual com luz fria, como se reconhecesse sangue, cargo ou senha. O corredor inteiro parece decidir se voce e visitante, sucessor ou estagiario enviado para morrer.",
      "scene.torch_corridor.choice_skeletons": "Aproximar-se dos esqueletos despertos",
      "scene.torch_corridor.choice_symbol": "Encostar o manual no sigilo pulsante",
      "scene.torch_corridor.choice_back": "Voltar ao hall de entrada",
      "scene.skeleton_clash.body": "Os esqueletos se levantam por completo agora. Nao tropeçam nem fazem drama; movem-se com a frieza eficiente de quem ja participou de cento e quarenta validacoes. Um deles usa ainda restos de cracha sobre a caixa toracica. Outro traz no cranio uma rachadura remendada com fita escura como se tivesse sobrevivido a uma migracao de ferramenta. Quando viram para voce ao mesmo tempo, sente algo pior que perigo: sente a tentacao de descobrir se consegue colocá-los para documentar tudo em seu nome.",
      "scene.skeleton_clash.choice_attack": "Atacar antes que abram uma planilha",
      "scene.skeleton_clash.choice_command": "Ordenar que se ajoelhem em nome do manual",
      "scene.skeleton_clash.choice_defy": "Erguer o cartao do mentor e recusar o culto da produtividade morta",
      "scene.sealed_gate.body": "O sigilo responde como notebook em superaquecimento. Linhas azuis correm pela parede, o corredor treme e uma porta oculta se desenha onde antes havia concreto. Pela fenda, voce ve uma pequena escada e, muito alem dela, um brilho azul enterrado em sombra. O manual pulsa com alegria quase humana. Uma lembranca roubada atravessa sua mente: la embaixo nao dorme apenas poder. Dorme a trilha ate a Gema Azul, o artefato que promete o design system definitivo, aquele que poderia dobrar equipes, revisoes e realidade ao mesmo grid.",
      "scene.sealed_gate.choice_open": "Abrir a porta interna e descer o ultimo lance",
      "scene.sealed_gate.choice_kneel": "Ajoelhar-se e aceitar o chamado agora",
      "scene.sealed_gate.choice_flee": "Fugir com o segredo antes que ele vire sua personalidade",
      "scene.watcher_door.body": "A camara interior e menor do que a visao prometia, mas muito mais humilhante. Um trono de pedra rachada repousa ao fundo, cercado por placas com nomes de produtos apagados por unhas ou cortes de budget. Sobre o assento, incrustada na rocha, ha apenas uma lasca mineral azul que ainda assim parece profunda demais, como se contivesse guideline em vez de materia. Ao encara-la, voce entende duas coisas ao mesmo tempo: aquilo nao e a Gema Azul, mas pertence a ela; e sua carreira jamais voltara a ser simples.",
      "scene.watcher_door.choice_seek_power": "Jurar que encontrara a Gema Azul antes de qualquer PM ou consultor",
      "scene.watcher_door.choice_destroy": "Jurar que destruira a Gema Azul, mesmo que isso acabe com seu portfolio",
      "scene.watcher_door.choice_seek_allies": "Levar a verdade aos vivos e buscar devs, writers e sobreviventes",
      "scene.ending_skeletons.body": "Voce avanca antes que o medo vire burocracia. O primeiro golpe derruba um cranio cheio de checklist, mas tres lanças enferrujadas de apontamento surgem ao mesmo tempo. O corredor se fecha em osso, metal e luz de monitor. Quando cai, entende tarde demais que o terminal nao prometia liberdade. Prometia dono.",
      "scene.ending_pact.body": "Diante da porta aberta e do brilho que jamais deveria caber num unico token, voce escolhe nao recuar. Ja nao ve apenas um manual, um subsolo ou um erro de carreira. Ve uma trilha. Quando jura buscar a Gema Azul, o livro esfria nas suas maos como se enfim estivesse satisfeito. No andar de cima, o expediente continua igual para o resto do mundo. Para voce, ele acabou. O que nasce nesta camara nao e so ambicao, mas a devocao de alguem que talvez passe seculos tentando padronizar o universo.",
      "scene.ending_broken.body": "Voce foge da camara antes de tocar a lasca azul, mas nao sai inteiro. A cada passo de volta, a palavra destruicao mistura-se a outras: guideline, token, sistema, dependencia. Parte de voce escapou do fascinio. Outra parte ficou para sempre encostada naquela luz enterrada. Quando enfim ve o andar principal outra vez, ja sabe que passara anos, talvez empregos, procurando a Gema Azul para destrui-la antes que ela termine de transformar toda conversa em discussao sobre componentes.",
      "scene.ending_allies.body": "Voce nao se ajoelha. Tambem nao finge que pode esquecer. Recolhe o que viu, fecha a jaqueta sobre o manual e deixa a camara levando nao uma resposta, mas uma responsabilidade absurda. Se a Gema Azul existe, voce nao pode enfrenta-la sozinho, nem permitir que essa febre amadureca em segredo. Ao sair do subsolo, o estudio parece maior, mais ridiculo e estranhamente mais humano. Pela primeira vez, a salvacao nao parece estar no controle absoluto, mas em encontrar uma equipe que ria antes que tudo vire culto.",
      "scene.ending_cowardice.body": "Antes do fim do expediente, voce fecha a bolsa, pede um carro por aplicativo e some sem olhar para tras. Ainda assim, na noite seguinte, sonha com paginas abrindo sozinhas, skeleton loaders e dedos descarnados apontando para um botao azul no escuro. O manual nao lhe pertence. Mas ja conhece seu nome."
    },
    en: {
      "mode.designer.title": "The Designer Who Discovered the Terminal",
      "mode.designer.menu": "Designer Journey",
      "mode.designer.description": "A secret parody about design, terminals, and terrible decisions.",
      "mode.designer.unlock": "SECRET UNLOCKED: The Designer Who Discovered the Terminal.",
      "ui.ending": "END OF PROTOTYPE",
      "ui.footer": "Designer Terminal Engine v0.1",
      "item.mentor_token": "mentor spacing card",
      "item.black_grimoire": "forbidden terminal manual",
      "chapter.1.title": "Introduction to the Brief",
      "chapter.1.summary": "You still think you are about to open Figma. The terminal disagrees.",
      "chapter.2.title": "The Wireframe Catacombs",
      "chapter.2.summary": "Dead folders, forgotten flows, and comments without owners.",
      "chapter.3.title": "Inside the Backlog Dungeons",
      "chapter.3.summary": "Tickets that never die, scope that swells, and rituals of endless review.",
      "chapter.4.title": "The Secrets of the Ancient Design System",
      "chapter.4.summary": "Forbidden tokens, lost grids, and the old obsession with the perfect blue.",
      "chapter.5.title": "UX and Its Horrors",
      "chapter.5.summary": "The escape from the library and the temple of absolute layout.",
      "rules.intro": "You can play this parody by simply choosing the options on screen, or use a d6 to simulate approvals, rework, courage to defend an idea, and mental resistance against meetings that should have been email.",
      "rules.note": "The die is still optional. If you prefer, you can simply decide how this designer loses their peace.",
      "menu.subtitle": "A young designer finds the terminal and learns that alignment, spacing, and sanity are all negotiable.",
      "menu.intro": "On the day you turn twenty, you swear you will work only with beautiful screens, clean grids, and comments that make sense. Then a forbidden terminal manual appears, your mentor is gone, and an indecent promise takes root: total control over a project without opening a single Figma window.",
      "scene.intro_home.body": "Mistash Studio wakes to the smell of old coffee, mechanical keyboards, and silent Monday dread. Today you turn twenty. A junior designer, a half-elf, and the last apprentice of Edrin of Art Direction, you are ready to leave the safety of academic mockups and face real projects. But the morning arrives wrong: a freelancer has been found collapsed on the north road, and their bag bears strange marks, as though sealed by an entity that despises manual alignment.",
      "scene.intro_home.choice_tower": "Climb to Edrin's old studio before taking the brief",
      "scene.intro_home.choice_inn": "Go straight to the coworking floor and inspect the freelancer's bag",
      "scene.mentor_room.body": "Edrin's studio still holds dried markers, forgotten post-its, and the smell of a retired projector. On a crooked desk you find the spacing card he used whenever a student tried to solve everything with shadows and gradients: 'Every interface demands payment. The one that promises total control takes the team's patience first.' Beside it lies an unfinished note about old tools that seduce the ego before they devour the calendar.",
      "scene.mentor_room.choice_keep_token": "Take the spacing card and head down into chaos",
      "scene.mentor_room.choice_leave": "Keep the lesson in your chest and walk away",
      "scene.intro_study.body": "At the coworking floor, the freelancer has already been taken to the quiet room, but the bag still rests on the main table under a ring of guilty eyes. Because you are the only person nearby who knows where the font folder is and can open a terminal without sweating, you are asked to inspect the clasps and stickers. Inside waits a black manual, cold as a sleeping monitor. Even closed, it seems to pulse. Its title promises a forgotten art: mastering whole projects without relying on windows, panels, or polite clicks.",
      "scene.intro_study.choice_open": "Open the forbidden manual",
      "scene.intro_study.choice_origin": "Study its marks and discover where it came from",
      "scene.intro_study.choice_refuse": "Close the bag and pretend none of this is your problem",
      "scene.traveler_markings.body": "Beneath the bag's lining, you find hidden pockets full of unlabeled cables, a hand-drawn map of the building, and three journal pages glued together by dried coffee. There is no name, only feverish phrases: 'the basement where developers speak softly,' 'guards that review without blinking,' 'the Blue Gem is not a token, it is a disease.' The final line tilts as though written during a daily that ran twenty minutes too long. Blue dust clings to the seams, fine as premium brand pigment.",
      "scene.traveler_markings.choice_journal": "Read the journal to its last line and return to the manual",
      "scene.traveler_markings.choice_shrine": "Go to the quiet room and see the freelancer",
      "scene.shrine_body.body": "In the quiet room, the freelancer rests in an ergonomic chair that has long since abandoned its marketing promise. The face looks ten sprints older than it should. When you move the scarf from the neck, you find a narrow mark near the collarbone, too fine to be a bag strap and far too cold to be simple exhaustion. Around it lies faded blue dust, as if someone had ground a brand manual into powder and blown it into a soul.",
      "scene.shrine_body.choice_wound": "Study the mark and carry that image with you",
      "scene.shrine_body.choice_leave": "Cover the freelancer and leave before guilt sits beside you",
      "scene.whispering_book.body": "The pages move almost by themselves beneath the office lights. There are stories of teams that abandoned graphical tools, of designers who began shaping flows through pure text, of people who organized chaos, assets, and deploys without touching a sidebar. Ever since Edrin vanished from the trade, you have spent your days pretending design is still only about form and taste. Now the manual gives words to a desire you never confessed: if the project can be described, perhaps it can be controlled. The book speaks not only of productivity. It answers your fear of never being enough. And it calls your name.",
      "scene.whispering_book.choice_follow_call": "Follow the hidden map into the basement",
      "scene.whispering_book.choice_resist": "Fight the fascination and step outside",
      "scene.whispering_book.choice_token": "Clutch Edrin's card and go anyway",
      "scene.camp_retreat.body": "Outside, cold air returns the sounds that used to feel normal: a phone vibration, a motorcycle in the street, someone saying 'let's sync offline.' You try to cling to that, to breathe, to remember Edrin saying no tool can save a broken brief. It fails. Every blink brings command lines, layouts conjured from text, and the indecent promise of never wasting twenty minutes hunting the right button again. The more you resist, the more the terminal sounds like eternal life for someone exhausted by endless review.",
      "scene.camp_retreat.choice_return": "Yield to the call and follow the manual's map",
      "scene.camp_retreat.choice_shrine": "Visit the quiet room first and face the freelancer",
      "scene.camp_retreat.choice_end": "Call a car and vanish before the next alignment",
      "scene.threshold_road.body": "Before lunch, you leave the main floor behind and follow the route scratched between the manual's pages. The path crosses abandoned meeting rooms, a storage closet of old campaign swag, and corridors where a thousand doomed print jobs went to die. Beneath your arm, the book pulses at measured intervals, as if it knows each step takes you farther from the comfort of interfaces and closer to something that writes faster than you think.",
      "scene.threshold_road.choice_ossuary": "Examine the graveyard of old projects",
      "scene.threshold_road.choice_press_on": "Go straight to the old server chapel",
      "scene.threshold_road.choice_turn_back": "Stop and reconsider before descending further",
      "scene.war_ossuary.body": "Moving aside boxes and printed mockups, you find no trophies and no portfolios, only campaign remains, dead pantones, and the skeletal frame of a brand once called disruptive. It is the first time you have faced legacy work up close: heavy posters, bad naming, and a corporate mascot with orc tusks. The shock comes not from exotic horror, but from knowing someone once defended this in a meeting. Between warped sheets lie black plastic beads and a blue card stamped with a perfect circle, like a UI token that refuses to die.",
      "scene.war_ossuary.choice_search": "Carry the image with you and continue to the chapel",
      "scene.war_ossuary.choice_leave": "Put it back and pretend respect for the dead of branding",
      "scene.chapel_yard.body": "The old server chapel rises among cold walls like a buried showroom. Part of the ceiling has collapsed, thick cables pierce the roof, and the air smells of dust, metal, and unlicensed fonts. Near the entrance rests the freelancer's laptop, dead without battery and covered in stickers for stacks they may never have used. Beneath the grime of the hall, a nearly erased mural shows a figure kneeling before a blue button upheld by skeletal hands. Someone scraped at it in fury, but the devotion remains.",
      "scene.chapel_yard.choice_descend": "Cross the hall and descend",
      "scene.chapel_yard.choice_fresco": "Study the mural before entering",
      "scene.chapel_yard.choice_leave": "Retreat while there is still life outside this place",
      "scene.entry_hall.body": "Guided by the manual and by a curiosity that now feels like ambition, you cross the server chapel and reach the basement entry hall. Cracked columns hold the ceiling, faceless mannequins seem to review your portfolio, and the damp smells of hot metal, abandoned coffee, and expired deadlines. To the right, a corridor of blue monitors pulses like something alive. At the center, a slab of stone and cables forms an altar of visual tokens. To the left, deep niches keep campaign folders buried beneath administrative silence.",
      "scene.entry_hall.choice_altar": "Examine the altar of tokens",
      "scene.entry_hall.choice_gallery": "Enter the gallery of buried projects",
      "scene.entry_hall.choice_torch": "Take a maintenance light and follow the pulsing corridor",
      "scene.altar_room.body": "There are no common offerings on the altar, only broken style guides, printed grids, and little rectangles aligned as if they formed a sentence in eight-point type. The manual vibrates in your hands. In the margin of a once-empty page, new lines rise in blue rust. They speak of an heir, of inner interfaces, and of a will that refuses arbitrary spacing. This is not a text for any reader. It is a text for someone willing to call this a system.",
      "scene.altar_room.choice_read_margin": "Read the new lines to the end",
      "scene.altar_room.choice_leave": "Step away before the typography enters your bloodstream",
      "scene.scroll_vision.body": "When the final line is read, you stagger. For an instant you are no longer in the basement but in a buried auditorium before an empty throne ringed by crowned wireframes. Something watches from behind the seat, patient as a guideline and hungry as rework. Then comes a thought not born from you: 'Alignment is a prison for the lesser. For you, it shall be empire.' It does not sound like a promise. It sounds like onboarding.",
      "scene.scroll_vision.choice_forward": "Follow the auditorium-memory to the next door",
      "scene.scroll_vision.choice_retreat": "Steady your breathing and return to the corridor",
      "scene.bone_gallery.body": "The niches hold dead campaigns, dusty prototypes, and chains of comments fixed to hooks of stone. At the back, a figure sits bound to a chair: neither creative nor fully retired. The skin has tightened against the bones like someone who spent three years in bad lighting, and the fingers still move in tiny gestures, as if adjusting an invisible frame. For the first time, you understand an undead stakeholder not as a joke, but as a material offense against rest.",
      "scene.bone_gallery.choice_chain": "Approach the chained figure",
      "scene.bone_gallery.choice_leave": "Leave the gallery and seek the main corridor",
      "scene.grave_answer.body": "As you draw close, the shriveled face lifts with the slow snap of someone about to say, 'just one small tweak.' There is no life there, only leftover opinion. One dry eye still fills its socket like a misaligned mockup dot, and the mouth opens too slowly to suggest urgency. Before any sound emerges, the manual grows warm under your arm, as if it recognizes in that ruin a renewable source of feedback. The air grows heavy in an almost corporate way, as though silence itself awaited a pitch.",
      "scene.grave_answer.choice_question": "Use the manual and demand that the dead give feedback",
      "scene.grave_answer.choice_mercy": "Touch Edrin's card to its brow and grant silence",
      "scene.grave_answer.choice_leave": "Step back without learning how many revisions still live here",
      "scene.torch_corridor.body": "The blue monitors tremble without wind as you approach. Ahead, narrow shadows rise from the floor: skeletons of QA and compliance, each made from ordinary human bones yet moved by the urge to point out what no one else saw. On the wall beside them, a circular sigil answers the manual with cold light, as though it recognizes blood, title, or password. The corridor seems to be deciding whether you are visitor, successor, or intern sent to die.",
      "scene.torch_corridor.choice_skeletons": "Approach the awakened skeletons",
      "scene.torch_corridor.choice_symbol": "Press the manual against the pulsing sigil",
      "scene.torch_corridor.choice_back": "Return to the entry hall",
      "scene.skeleton_clash.body": "The skeletons rise fully now. They do not stumble or posture; they move with the efficient chill of creatures that have survived one hundred and forty validation rounds. One still wears the remains of an ID badge across the ribs. Another bears a fracture repaired with dark tape, as though it endured a migration of tools and never recovered. When they all turn toward you at once, you feel something worse than danger: the temptation to see if you can make them document everything in your name.",
      "scene.skeleton_clash.choice_attack": "Strike before they open a spreadsheet",
      "scene.skeleton_clash.choice_command": "Order them to kneel in the manual's name",
      "scene.skeleton_clash.choice_defy": "Raise the mentor's card and reject the cult of dead productivity",
      "scene.sealed_gate.body": "The sigil answers like an overheating laptop. Blue lines race across the wall, the corridor shudders, and a hidden door sketches itself out of concrete. Through the crack you see a short stair and, far beyond it, a blue gleam buried in shadow. The manual pulses with almost human delight. A stolen memory slices through your mind: what lies below is not merely power. It is the path toward the Blue Gem, the artifact that promises the definitive design system, the one that could bend teams, revision cycles, and reality itself to a single grid.",
      "scene.sealed_gate.choice_open": "Open the inner door and descend the final stair",
      "scene.sealed_gate.choice_kneel": "Kneel and accept the call now",
      "scene.sealed_gate.choice_flee": "Flee with the secret before it becomes your personality",
      "scene.watcher_door.body": "The inner chamber is smaller than the vision promised, but far more humiliating. A cracked stone throne rests at the back, ringed by plaques bearing product names scraped away by nails and budget cuts. Set into the seat is only a blue shard that still seems too deep, as though it contained guidelines instead of matter. Looking at it, you understand two things at once: this is not the Blue Gem, but it belongs to it; and your career will never be simple again.",
      "scene.watcher_door.choice_seek_power": "Swear you will find the Blue Gem before any PM or consultant",
      "scene.watcher_door.choice_destroy": "Swear you will destroy the Blue Gem, even if it ruins your portfolio",
      "scene.watcher_door.choice_seek_allies": "Carry the truth to the living and seek devs, writers, and survivors",
      "scene.ending_skeletons.body": "You move before fear can become process. The first strike shatters a skull full of checklists, but three rusted spears of feedback thrust from the dark at once. The corridor closes in with bone, metal, and monitor-light. As you fall, you understand too late that the terminal offered no freedom. It offered ownership.",
      "scene.ending_pact.body": "Before the open door and the gleam that should never fit inside a single token, you choose not to retreat. You no longer see a manual, a basement, or a poor career choice. You see a path. When you swear to seek the Blue Gem, the book turns cold in your hands as if at last satisfied. Upstairs, the workday remains unchanged for everyone else. For you, it is over. What is born in that chamber is not merely ambition, but the devotion of someone who may spend centuries trying to standardize the universe.",
      "scene.ending_broken.body": "You flee the chamber before touching the blue shard, but you do not leave whole. With every step back, the word destruction tangles with others: guideline, token, system, dependency. Part of you escaped the fascination. Another part remained forever turned toward that buried light. When you finally reach the main floor again, you already know you will spend years, perhaps jobs, seeking the Blue Gem to destroy it before it turns every conversation into a component argument.",
      "scene.ending_allies.body": "You do not kneel. Neither do you pretend you can forget. You gather what you have seen, close your jacket over the manual, and leave the chamber carrying not an answer but an absurd responsibility. If the Blue Gem exists, you cannot face it alone, nor let this fever mature in secret. When you emerge from the basement, the studio feels larger, more ridiculous, and strangely more human. For the first time, salvation does not seem to live in total control, but in finding a team that can still laugh before everything becomes cult.",
      "scene.ending_cowardice.body": "Before the workday ends, you close the bag, call a ride, and vanish without looking back. Yet the following night you dream of pages opening on their own, skeleton loaders, and stripped fingers pointing toward a blue button in the dark. The manual does not belong to you. But it already knows your name."
    }
  }
};
